add "Transaction rolled back" for invalid batons inside transactions #1856
tursodatabase/libsql pull request #1860
Opened 2024-12-01 00:48 UTC by levydsa

2024-12-02 17:18 UTC, penberg approved these changes
Looks good to me. @LucioFranco please review too.

2024-12-02 21:35 UTC, LucioFranco requested changes
The PR needs a description with motivation for this change, we should add that and ensure its in the commit messages.

That said, I think it would be smarter to emit this error from the server rather than the client? That way users don't need to update their client to get this improvement?

2024-12-22 15:27 UTC, MrG9090 approved these changes

2025-03-20 10:20 UTC, penberg commented
Unfortunately there is no trace of us discussing this, but I think we agreed not to do this. Closing.

2025-03-20 10:20 UTC, closed without merging