make libsql client a valid target for cloudflare workers
tursodatabase/libsql pull request #504
Opened 2023-10-24 00:41 UTC by Horusiath

This PR introduces new feature: `cloudflare-worker`, which enables Hrana protocol to be served over Cloudflare workers.

Current blocker: a plenty of `async_trait` interfaces are not compatible with Cloudflare worker API, which uses structs that are not `Send + Sync`.

2023-10-24 01:08 UTC, Horusiath commented on libsql/src/connection.rs
> +#[cfg_attr(not(feature = "cloudflare-worker"), async_trait::async_trait)]
Any advice on how to make it cleaner? @LucioFranco ?

2023-10-24 14:21 UTC, LucioFranco requested changes
No real request changes yet because I don't know exactly what path we should take.

2023-10-24 14:21 UTC, LucioFranco commented on libsql/src/local/impls.rs
> +#[cfg_attr(not(feature = "hrana-cf"), async_trait::async_trait)]
I don't think this is the right approach we should take since we need these features to be additive.

2023-10-30 02:52 UTC, Horusiath commented on .gitignore
> +.idea/
Same could be said about `.vscode/` path ;)

2023-11-30 05:35 UTC, Horusiath commented
1.

2023-11-30 05:35 UTC, closed without merging