libsql: fix deferred txn with embedded replicas
tursodatabase/libsql pull request #559
Opened 2023-11-02 18:44 UTC by LucioFranco

This fixes an issue where embedded replica based connections would have issues dispatching executes on deferred statements. This is due to sqld using `sqlite3_txn_state` to return the connection's state. While this works for other transactions, in a deferred transaction the connection does not change its state to be in a transaction. This is due to the nature of a deferred transaction. The problem is that the connection does set `is_autocommit` to `false`. This means that sqld is returning that it is not in a txn state which is used by clients to set its `is_autocommit` state. For now the work around is to track when the client is in a `DEFERRED` transaction and to handle remote state transition's in such a way that it ignores the value from the server if it is currently in the deferred state.

2023-11-02 18:50 UTC, psarna requested changes
One change is needed in the state transition code, but I have a more fundamental question.

Why would we use `sqlite3_txn_state` to determine autocommit mode in sqld, if we have `sqlite3_get_autocommit`? https://www.sqlite.org/c3ref/get_autocommit.html

2023-11-02 18:50 UTC, psarna commented on libsql/src/replication/connection.rs
>              (_, StmtKind::Savepoint) => State::Invalid,
So we also now need
```rust
(State::TxnDeferred, StmtKind::Savepoint) => State::TxnDeferred
```
, and same for Release, right?

2023-11-02 19:01 UTC, psarna approved these changes

2023-11-07 14:09 UTC, LucioFranco commented
Fixed via https://github.com/tursodatabase/libsql/pull/577

2023-11-07 14:09 UTC, closed without merging